## 1. Introduction
<p><img src="https://assets.datacamp.com/production/project_1197/img/google_play_store.png" alt="Google Play logo"></p>
<p>Mobile apps are everywhere. They are easy to create and can be very lucrative from the business standpoint. Specifically, Android is expanding as an operating system and has captured more than 74% of the total market<sup><a href="https://www.statista.com/statistics/272698/global-market-share-held-by-mobile-operating-systems-since-2009">[1]</a></sup>. </p>
<p>The Google Play Store apps data has enormous potential to facilitate data-driven decisions and insights for businesses. In this notebook, we will analyze the Android app market by comparing ~10k apps in Google Play across different categories. We will also use the user reviews to draw a qualitative comparision between the apps.</p>
<p>The dataset you will use here was scraped from Google Play Store in September 2018 and was published on <a href="https://www.kaggle.com/lava18/google-play-store-apps">Kaggle</a>. Here are the details: <br>
<br></p>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:20px"><b>datasets/apps.csv</b></div>
This file contains all the details of the apps on Google Play. There are 9 features that describe a given app.
<ul>
    <li><b>App:</b> Name of the app</li>
    <li><b>Category:</b> Category of the app. Some examples are: ART_AND_DESIGN, FINANCE, COMICS, BEAUTY etc.</li>
    <li><b>Rating:</b> The current average rating (out of 5) of the app on Google Play</li>
    <li><b>Reviews:</b> Number of user reviews given on the app</li>
    <li><b>Size:</b> Size of the app in MB (megabytes)</li>
    <li><b>Installs:</b> Number of times the app was downloaded from Google Play</li>
    <li><b>Type:</b> Whether the app is paid or free</li>
    <li><b>Price:</b> Price of the app in US$</li>
    <li><b>Last Updated:</b> Date on which the app was last updated on Google Play </li>

</ul>
</div>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:20px"><b>datasets/user_reviews.csv</b></div>
This file contains a random sample of 100 <i>[most helpful first](https://www.androidpolice.com/2019/01/21/google-play-stores-redesigned-ratings-and-reviews-section-lets-you-easily-filter-by-star-rating/)</i> user reviews for each app. The text in each review has been pre-processed and passed through a sentiment analyzer.
<ul>
    <li><b>App:</b> Name of the app on which the user review was provided. Matches the `App` column of the `apps.csv` file</li>
    <li><b>Review:</b> The pre-processed user review text</li>
    <li><b>Sentiment Category:</b> Sentiment category of the user review - Positive, Negative or Neutral</li>
    <li><b>Sentiment Score:</b> Sentiment score of the user review. It lies between [-1,1]. A higher score denotes a more positive sentiment.</li>

</ul>
</div>
<p>From here on, it will be your task to explore and manipulate the data until you are able to answer the three questions described in the instructions panel.<br></p>

## 1. Read the apps data and clean the installs column

In [72]:
# Import dataset
import pandas as pd
apps = pd.read_csv('datasets/apps.csv')
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0.0,"June 20, 2018"

In [73]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 9 columns):
App             9659 non-null object
Category        9659 non-null object
Rating          8196 non-null float64
Reviews         9659 non-null int64
Size            8432 non-null float64
Installs        9659 non-null object
Type            9659 non-null object
Price           9659 non-null float64
Last Updated    9659 non-null object
dtypes: float64(3), int64(1), object(5)
memory usage: 679.2+ KB

In [74]:
apps['Installs'] = apps['Installs'].str.replace('+',"")
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000",Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000",Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000",Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000",Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000",Free,0.0,"June 20, 2018"

In [75]:
apps['Installs'] = apps['Installs'].str.replace(',',"").astype(int)

In [76]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 9 columns):
App             9659 non-null object
Category        9659 non-null object
Rating          8196 non-null float64
Reviews         9659 non-null int64
Size            8432 non-null float64
Installs        9659 non-null int64
Type            9659 non-null object
Price           9659 non-null float64
Last Updated    9659 non-null object
dtypes: float64(3), int64(2), object(4)
memory usage: 679.2+ KB

## 2. Find the number of apps in each category, the average price, and the average rating

In [77]:
app_category_info =  apps.groupby('Category').agg({'App':'count', 'Price':'mean', 'Rating':'mean'})
columns=['Number of apps', 'Average price', 'Average rating']
app_category_info.columns = columns

In [78]:
app_category_info =  app_category_info.reset_index()
app_category_info

               Category  Number of apps  Average price  Average rating
0        ART_AND_DESIGN              64       0.093281        4.357377
1     AUTO_AND_VEHICLES              85       0.158471        4.190411
2                BEAUTY              53       0.000000        4.278571
3   BOOKS_AND_REFERENCE             222       0.539505        4.344970
4              BUSINESS             420       0.417357        4.098479
5                COMICS              56       0.000000        4.181481
6         COMMUNICATION             315       0.263937        4.121484
7                DATING             171       0.160468        3.970149
8             EDUCATION             119       0.150924        4.364407
9         ENTERTAINMENT             102       0.078235        4.135294
10               EVENTS              64       1.718594        4.435556
11               FAMILY            1832       1.309967        4.179664
12              FINANCE             345       8.408203        4.115563
13       FOOD_AND_DRINK             112       0.075714        4.172340
14                 GAME             959       0.296465        4.247368
15   HEALTH_AND_FITNESS             288       0.223438        4.243033
16       HOUSE_AND_HOME              74       0.000000        4.150000
17   LIBRARIES_AND_DEMO              84       0.011786        4.178125
18            LIFESTYLE             369       6.398022        4.093355
19  MAPS_AND_NAVIGATION             131       0.205725        4.036441
20              MEDICAL             395       2.520759        4.166552
21   NEWS_AND_MAGAZINES             254       0.015669        4.121569
22            PARENTING              60       0.159667        4.300000
23      PERSONALIZATION             376       0.400213        4.332215
24          PHOTOGRAPHY             281       0.420925        4.157414
25         PRODUCTIVITY             374       0.670936        4.183389
26             SHOPPING             202       0.027129        4.230000
27               SOCIAL             239       0.066820        4.247291
28               SPORTS             325       0.307692        4.216154
29                TOOLS             827       0.323156        4.039554
30     TRAVEL_AND_LOCAL             219       0.228082        4.069519
31        VIDEO_PLAYERS             163       0.064172        4.044595
32              WEATHER              79       0.410380        4.243056

## 3. Find the top 10 free FINANCE apps having the highest average sentiment score

In [79]:
reviews = pd.read_csv('datasets/user_reviews.csv')
reviews.head()

,App,Review,Sentiment Category,Sentiment Score
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25
2,10 Best Foods for You,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40
4,10 Best Foods for You,Best idea us,Positive,1.00

In [80]:
free_finance = apps[(apps['Category'] == 'FINANCE') & (apps['Type'] == 'Free')]

In [81]:
free_finance.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
837,K PLUS,FINANCE,4.4,124424,NaN,10000000,Free,0.0,"June 26, 2018"
838,ING Banking,FINANCE,4.4,39041,NaN,1000000,Free,0.0,"August 3, 2018"
839,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018"
840,The postal bank,FINANCE,3.7,36718,NaN,5000000,Free,0.0,"July 16, 2018"
841,KTB Netbank,FINANCE,3.8,42644,19.0,5000000,Free,0.0,"June 28, 2018"

In [82]:
user_feedback = reviews.merge(free_finance, on='App', how='inner')
user_feedback.head()

,App,Review,Sentiment Category,Sentiment Score,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,A+ Mobile,NaN,NaN,NaN,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
1,A+ Mobile,"I rated higher, lowering rating. It simply wor...",Negative,-0.063889,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
2,A+ Mobile,NaN,NaN,NaN,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
3,A+ Mobile,NaN,NaN,NaN,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"
4,A+ Mobile,It tells I need update option update. So I uni...,Positive,0.156250,FINANCE,3.9,730,6.3,10000,Free,0.0,"June 26, 2018"

In [83]:
top_10_user_feedback = user_feedback.groupby('App')['Sentiment Score'].mean()

In [84]:
top_10_user_feedback = top_10_user_feedback.sort_values(ascending=False)

In [85]:
top_10_user_feedback = top_10_user_feedback.head(10)

In [86]:
colz= ['Sentiment Score']
top_10_user_feedback.columns=colz
top_10_user_feedback = pd.DataFrame(top_10_user_feedback)

In [87]:
top_10_user_feedback

                                            Sentiment Score
App
BBVA Spain                                         0.515086
Associated Credit Union Mobile                     0.388093
BankMobile Vibe App                                0.353455
A+ Mobile                                          0.329592
Current debit card and app made for teens          0.327258
BZWBK24 mobile                                     0.326883
Even - organize your money, get paid early         0.283929
Credit Karma                                       0.270052
Fortune City - A Finance App                       0.266966
Branch                                             0.264230